scrape_configs:
  - job_name: 'nginx-exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx_exporter:9113']
  - job_name: 'web-django'
    scrape_interval: 5s
    metrics_path: '/api/prometheus/v1/metrics'
    static_configs:
      - targets: ['web:8000']
  - job_name: 'nn-metrics'
    scrape_interval: 5s
    metrics_path: '/api/v3/metrics/metrics'
    static_configs:
      - targets: ['web:8000']
  - job_name: 'web-system'
    scrape_interval: 5s
    metrics_path: '/'
    static_configs:
      - targets: ['metrics_server:8003']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8020']

remote_write:
  - url: "http://carbon-clickhouse:2006"